
lle_easy_admin_plus_translations:
    path: /translations
    defaults:
        _controller: LleEasyAdminPlusBundle:Admin:translations

lle_easy_admin_plus_wf:
    path: /wf
    defaults:
        _controller: Lle\EasyAdminPlusBundle\Controller\AdminController::workflowAction


lle_easy_admin_plus:
    path: /
    defaults:
        _controller: LleEasyAdminPlusBundle:Admin:index
