services:
    wandi.easy_admin_plus.command.user.create:
        class: Wandi\EasyAdminPlusBundle\Command\UserCreateCommand
        tags:
            -  { name: console.command, command: wandi:easy-admin-plus:user:create }
    wandi.easy_admin_plus.command.user.change_password:
        class: Wandi\EasyAdminPlusBundle\Command\UserChangePasswordCommand
        tags:
            -  { name: console.command, command: wandi:easy-admin-plus:user:change-password }
    wandi.easy_admin_plus.command.user.enable:
        class: Wandi\EasyAdminPlusBundle\Command\UserEnableCommand
        tags:
            -  { name: console.command, command: wandi:easy-admin-plus:user:enable }
    wandi.easy_admin_plus.command.user.disable:
        class: Wandi\EasyAdminPlusBundle\Command\UserDisableCommand
        tags:
            -  { name: console.command, command: wandi:easy-admin-plus:user:disable }

    wandi.easy_admin_plus.translator:
        class: Wandi\EasyAdminPlusBundle\Translator\Translator
        public: true
        arguments:
            - '%easy_admin_plus%'
            - '%kernel.cache_dir%'

    wandi.easy_admin_plus.generator.base:
        abstract: true
        calls:
            - method: buildServiceConfig

    wandi.easy_admin_plus.generator.generate:
        class: Wandi\EasyAdminPlusBundle\Generator\Service\GeneratorGenerate
        arguments:
            - '@service_container'
        public: true
        parent: wandi.easy_admin_plus.generator.base

    wandi.easy_admin_plus.generator.clean:
        class: Wandi\EasyAdminPlusBundle\Generator\Service\GeneratorClean
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%easy_admin_plus%'
            - '%kernel.project_dir%'
            - '%kernel.bundles%'
        public: true

    wandi.easy_admin_plus.generator.entity:
        class: Wandi\EasyAdminPlusBundle\Generator\Service\GeneratorEntity
        arguments:
            - '@service_container'
        public: true
        parent: wandi.easy_admin_plus.generator.base

    wandi.easy_admin_plus.command.generator.generate:
        class: Wandi\EasyAdminPlusBundle\Command\GeneratorGenerateCommand
        tags:
            -  { name: console.command, command: wandi:easy-admin-plus:generator:generate }

    wandi.easy_admin_plus.command.generator.clean:
        class: Wandi\EasyAdminPlusBundle\Command\GeneratorCleanCommand
        tags:
            -  { name: console.command, command: wandi:easy-admin-plus:generator:cleanup }

    wandi.easy_admin_plus.command.generator.entity:
        class: Wandi\EasyAdminPlusBundle\Command\GeneratorEntityCommand
        tags:
            -  { name: console.command, command: wandi:easy-admin-plus:generator:entity }