services:
    lle.easy_admin_plus.translator:
        class: Lle\EasyAdminPlusBundle\Translator\Translator
        public: true
        arguments:
            - '%easy_admin_plus%'
            - '%kernel.cache_dir%'

    lle.easy_admin_plus.acl.security.admin_authorization_checker:
        class: Lle\EasyAdminPlusBundle\Acl\Security\AdminAuthorizationChecker
        public: true
        arguments:
            - '@security.authorization_checker'
    lle.easy_admin_plus.acl.event_listener.easy_admin_subscriber:
        class: Lle\EasyAdminPlusBundle\Acl\EventListener\EasyAdminSubscriber
        arguments:
            - '@lle.easy_admin_plus.acl.security.admin_authorization_checker'
        tags:
            - { name: kernel.event_subscriber }
    lle.easy_admin_plus.acl.helper.menu_helper:
        class: Lle\EasyAdminPlusBundle\Acl\Helper\MenuHelper
        arguments:
            - '@lle.easy_admin_plus.acl.security.admin_authorization_checker'
    lle.easy_admin_plus.acl.twig.menu_extension:
        class: Lle\EasyAdminPlusBundle\Acl\Twig\MenuExtension
        arguments:
            - '@lle.easy_admin_plus.acl.helper.menu_helper'
        tags:
            - { name: twig.extension }
    lle.easy_admin_plus.acl.twig.admin_authorization_extension:
        class: Lle\EasyAdminPlusBundle\Acl\Twig\AdminAuthorizationExtension
        arguments:
            - '@lle.easy_admin_plus.acl.security.admin_authorization_checker'
        tags:
            - { name: twig.extension }

    lle.easy_admin_plus.exporter.configuration.normalizer_config_pass:
        class: Lle\EasyAdminPlusBundle\Exporter\Configuration\NormalizerConfigPass
        public: true
        tags:
            - { name: easyadmin.config_pass }

    lle.easy_admin_plus.exporter.configuration.property_config_pass:
        class: Lle\EasyAdminPlusBundle\Exporter\Configuration\PropertyConfigPass
        public: true
        tags:
            - { name: easyadmin.config_pass }

    lle.easy_admin_plus.exporter.configuration.template_config_pass:
        class: Lle\EasyAdminPlusBundle\Exporter\Configuration\TemplateConfigPass
        public: true
        tags:
            - { name: easyadmin.config_pass }

    lle.easy_admin_plus.filter.configuration.property_config_pass:
        class: Lle\EasyAdminPlusBundle\Filter\Configuration\PropertyConfigPass
        public: true
        tags:
            - { name: easyadmin.config_pass }

    lle.easy_admin_plus.generator.base:
        abstract: true
        autowire: true
        calls:
            - method: buildServiceConfig
    lle.easy_admin_plus.generator.generate:
        class: Lle\EasyAdminPlusBundle\Generator\Service\GeneratorGenerate
        public: true
        parent: lle.easy_admin_plus.generator.base
    lle.easy_admin_plus.generator.clean:
        class: Lle\EasyAdminPlusBundle\Generator\Service\GeneratorClean
        public: true
        parent: lle.easy_admin_plus.generator.base
    lle.easy_admin_plus.generator.entity:
        class: Lle\EasyAdminPlusBundle\Generator\Service\GeneratorEntity
        public: true
        parent: lle.easy_admin_plus.generator.base

    lle.easy_admin_plus.command.generator.generate:
        class: Lle\EasyAdminPlusBundle\Generator\Command\GeneratorGenerateCommand
        tags:
            -  { name: console.command, command: lle:easy-admin-plus:generator:generate }
    lle.easy_admin_plus.command.generator.clean:
        class: Lle\EasyAdminPlusBundle\Generator\Command\GeneratorCleanCommand
        tags:
            -  { name: console.command, command: lle:easy-admin-plus:generator:cleanup }
    lle.easy_admin_plus.command.generator.entity:
        class: Lle\EasyAdminPlusBundle\Generator\Command\GeneratorEntityCommand
        tags:
            -  { name: console.command, command: lle:easy-admin-plus:generator:entity }
    twig.extension.stringloader:
        class: Twig_Extension_StringLoader
        tags:
            - { name: twig.extension }

    lle.easy_admin_plus.configuration.action_config_pass:
        class:  Lle\EasyAdminPlusBundle\Configuration\ActionConfigPass
        tags:
            - { name: easyadmin.config_pass, priority: 65}

    lle.easy_admin_plus.twig.extension:
        class: Lle\EasyAdminPlusBundle\Twig\LleEasyAdminPlusTwigExtension
        tags:
            - { name: twig.extension }
            
